const ALGERIA_CITIES = {
    "01": ["Adrar","Timimoun","Reggane","Aoulef","Deldoul","Tit","Tsabit","Zaouiet Kounta","Aougrout","Charouine","Tamest","Timiaouine"],
    "02": ["Chlef","Ténès","El Karimia","Talassa","Benairia","Mekdadra","Sobha","Sendjas","Zebadja"],
    "03": ["Laghouat","Aflou","Sidi Makhlouf","El Biod","Ksar El Hirane"],
    "04": ["Oum El Bouaghi","Aïn Beida","Aïn M'lila","El Amiria","Sigus","El Belala","El Khroub","Aïn Fakroun","Fkirina","Meskiana"],
    "05": ["Batna","Barika","N'Gaous","Guigba","Timgad","Merouana","Seriana","Chemora","Bouzina","Tazoult","Arris","Sefiane","Talkhamt","Ras El Aioun"],
    "06": ["Béjaïa","Akbou","Sidi Aïch","El Kseur","Kherrata","Tichy","Amizour","Feraoun","Ouzellaguen"],
    "07": ["Biskra","Tolga","Sidi Okba","M'Chouneche","Zeribet El Oued","Ouled Djellal","Ain Naga","Chetma","Lioua"],
    "08": ["Béchar","Boukhadra","Tabelbala","Kerzaz","Erg Ferradj"],
    "09": ["Blida","Boufarik","Bougara","Ben Thir","Chiffa","El Affroun","Mouzaïa","Mozzaïa","Larbaâ","Soumaa"],
    "10": ["Bouira","Sour El Ghozlane","Ain Bessem","El Hachimia","Ouled Rached","Dirrah","Taguedit"],
    "11": ["Tamanrasset","Abalessa","Tinzaouatine","In Guezzam","Idles","Tazrouk"],
    "12": ["Tébessa","Negrine","Bou Hatouf","Ech Chetma","Sakiet Sidi Youssef","Cheria"],
    "13": ["Tlemcen","Maghnia","Remchi","El Fehoul","Nedroma","Ghazaouet","Hennaya","Sabra","Beni Mester"],
    "14": ["Tiaret","Frenda","Aïn Deheb","Mahdia","Dahmouni","Rahouia","Mechraa Safa","Aïn Kermes","Medroussa"],
    "15": ["Tizi Ouzou","Aït Yahia","Azazga","Draâ El Mizan","Larbaâ Nath Iraten","Ouadhias","Maâtkas","Tigzirt","Aït Chaffaa","Iflissen"],
    "16": ["Alger","Bab Ezzouar","Hussein Dey","Kouba","Bir Mourad Raïs","Hydra","Bab El Oued","Sidi M'Hamed","El Biar","Bouzareah","Draria","Dely Ibrahim","Chéraga","Mohammadia"," Bordj El Kiffan","Rouiba","Reghaia","El Harrach","Baraki","Birtouta","Zeralda","Draria","Aïn Benian","Tipaza"],
    "17": ["Djelfa","Messaad","Aïn Oussera","Charef","El Iched","Hassi Bahbah","Sedrata","Aïn Chouhada","Dar El Kebd","Mlili"],
    "18": ["Jijel","El Milia","Taher","Skikda","El Ancer","Kaous","Guelata Boudria","Emdjez Edchich","Ziama Mansouriah"],
    "19": ["Sétif","El Eulma","Aïn Oulmene","Aïn Arnat","Bougaa","M'Array","El Ouricia","Benchela","Aïn Touta","Aïn Sefra"],
    "20": ["Saïda","El Hadjar","Aïn El Hadjar","Sidi Boubekeur","Hassi Dahou","Tircine","Aïn Soltane"],
    "21": ["Skikda","El Hadaiek","Azzaba","Zitouna","Ramdane Djamel","Ben Azzouz","Salah Bouchaour","Collo","Kanoua"],
    "22": ["Sidi Bel Abbés","Mérine","Tessala","Sfissef","Aïn El Berd","Mostefa Ben Brahim","Boukada","Tell","Sidi Lahcène","Aïn Thrid"],
    "23": ["Annaba","El Bouni","El Hadjar","Seraïdi","El Bouthaleb","Aïn El Berahim"],
    "24": ["Guelma","Bouati Mahmoud","Nechmaya","Aïn Benian","Hammam N'Bail","Khezara","Oued Zenati","Sانتa","Aïn Makhlouf","Tamlagant"],
    "25": ["Constantine","El Khroub","Aïn Smara","Didouche Mourad","Hamma Bouziane","Ali Mendjeli","Drebira","El Harissa","Ouled Rahmoune"],
    "26": ["Médéa","Berrouaghia","Ksar El Boukhari","Aïn Boucif","Aïn Sultane","Ouled Bouachra","Sidi Naâmane","Tablat","Oum El Djerad"],
    "27": ["Mostaganem","Aïn Tedles","Bouguirat","Sour","Khelifa Belkacem","Aïn El Kerma","Hassiane Ameur","Fornaka"],
    "28": ["M'sila","Bou Saâda","Aïn El Hadjel","Sidi Aïssa","Aïn El Melh","Hamra Dalaa","Khettara","Ouled Madhi","Aïn Fares"],
    "29": ["Mascara","Tighennif","Mohammadia","Sig","Gharrous","Oggaz","El Gaada","Froha","Tizi","Bouhanifia"],
    "30": ["Ouargla","Hassi Messaoud","Rouissat","Ngoussa","Hassi Ben Abdellah","Sidi Khouiled","Benaceur","El Borma"],
    "31": ["Oran","Bir El Djir","Aïn Turk","Es Senia","Arzew","Bethioua","Boufatis","Mers El Kébir","Aïn El Turck","Sidi Ben Yabka","El Kerma","Bou Sfer","Tafraoui"],
    "32": ["El Bayadh","Boualem","Bougtoub","El Abiodh Sidi Cheikh","El Bnoud","Chellala","El Kheiter","Kasdir","Bougara"],
    "33": ["Illizi","Bordj Badji Mokhtar","Debdeb","In Amenas","Bordj El Haouas"],
    "34": ["Bordj Bou Arréridj","Bou Gaâ","Ras El Oued","Bordj Ghdir","Belimour","Elhamadia","Tafreg","Colla","Tassamant"],
    "35": ["Boumerdès","Thénia","Boudouaou","Khemis El Khechna","Isser","Legata","Chabet El Ameur","Si Mustapha","Naceredine","El Kharrouba"],
    "36": ["El Tarf","Bouhadjar","Ben M'Hidi","Asfour","Echatt","El Aioun","Bouhgara","Raml Souk"],
    "37": ["Tindouf","Oum El Assel"],
    "38": ["Tissemsilt","Bordj Bou Naâma","Lazharia","Theniet El Had","Lardjem","Sidi Lantri","Bou Caid"],
    "39": ["El Oued","Guemar","Bayadha","Namous","Taleb Larbi","Douar En Naja","Sidi Aoun","Oued El Alenda","Robbah"],
    "40": ["Khenchela","Aïn Touila","Taouzianat","El Hamma","Boumia","Babar","Chelala","Ouled Rechache","El Mahmal"],
    "41": ["Souk Ahras","Sedrata","Haddada","M'daourouch","Ouled Driss","Merahna","El Hamri","Tiffilissane"],
    "42": ["Tipaza","Koléa","El Affroun","Cherchell","Sidi Ghiles","Bourkika","Beni Mileuk","Gouraya","Hadjeret Ennous"],
    "43": ["Mila","Tadjenanet","Ouled Errahbane","Sidi Merouane","Oued Athmania","Chigara","Rouached","Grarem Gouga","Tessala El Merdja"],
    "44": ["Aïn Defla","Miliana","Boumedfaa","Khemis Miliana","Hammam Righa","Aïn Torki","Aïn Benian","El Attaf","El Abadia","Rouina","Zeralda"],
    "45": ["Naâma","Méchéria","Aïn Sfara","El Biod","Kasdir","Moghrar","Sidi Amar","Ain Ben Khelil"],
    "46": ["Aïn Témouchent","El Amria","Hammam Bou Hadjar","Beni Saf","El Malah","Sidi Ben Adda","Aïn El Arbaa","El Gor","Chouala","Beni Chougrane"],
    "47": ["Ghardaïa","Metlili","El Guerrara","Dhayet Bendhahoua","Béchar","El Ogla","Berriane","Bounoura"],
    "48": ["Relizane","Mendes","Zemmoura","Beni Dergoun","Djidiouia","El Guenaoui","Hassein Abdelmalek","Mazouna","Oued Essalem","Oued Aghouni","Sidi Khettab","Ammi Moussa","Hamriya"],
    "49": ["El M'Ghair","El Anasser","Miaïdoune","Sidi Khelifa"],
    "50": ["El Meniaa","Hassi Fehal","Hassi Gara","Mansoura"],
    "51": ["Ouled Djellal","El Haouassed","Sidi Khaled","Douas","Bou Amer"],
    "52": ["Bordj Badji Mokhtar","Timiaouine"],
    "53": ["Béni Abbès","Ksabi","Tamtert","Igli"],
    "54": ["Timimoun","Charouine","Talmine"],
    "55": ["Touggourt","El Borma","Nezla","Taibat","Benaceur"],
    "56": ["Djanet","Bordj El Haouas"],
    "57": ["In Salah","Tamanrasset","Foggaret Ezzaouia"],
    "58": ["In Guezzam","Tinzaouatine"]
};
